### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by waltermvp** [c-Viorel/MBIcons#1]
What is the license for the use of this framework and its resources?

**Comment by c-Viorel** [comment]
It's free for commercial use

**Comment by waltermvp** [comment]
@c-Viorel that's awesome! thanks for this framework. Maybe adding a License would clarify any future questions. I can send a PR later today if you'd like.

**Comment by c-Viorel** [comment]
You're welcome! if not too much trouble for you, a PR will be awesome.

**Comment by sethmlarson** [comment]
It would be a bad idea to let users choose a license to use for your code because what we choose may be completely different from how you intended your code to be used. Instead take a few minutes to preview [this website](https://choosealicense.com/), choose a license, and then paste the plaintext contents of the license from that website into a `LICENSE.txt` file in the project root. You may also want to look at [Creative Commons licenses](https://creativecommons.org/), as the licenses on choosealicense.com are geared more towards code.

**Comment by c-Viorel** [comment]
I wasn't about to merge that PR until i'll read it. But you are right. It took 5 minutes to add licence file. Thanks.
